import tkinter as t
root=t.Tk()
def clear():
    slide1.set(0)
    slide2.set(100)
    slide3.set(200)
    slide4.set(000)
def max():
    slide2.set(200)
    slide1.set(100)
    slide3.set(300)
def avg():
    slide1.set(50)
    slide2.set(150)
    slide3.set(200)
    slide4.set(slide3.get()+slide2.get())
def slide_add():
    slide1.set(slide1.get()+5)
    slide2.set(slide2.get()+5)
    slide3.set(slide3.get()+5)
def slide_sub():
    slide1.set(slide1.get()-5)
    slide2.set(slide2.get()-5)
    slide3.set(slide3.get()-5)
def auto():
    slide4.set(slide2.get()+slide3.get())
    first_val.set(slide4.get())
root.title ("Slider")
first_val=t.IntVar()
first_val.set(10)
#print(lambda :color())
color=first_val.get()
print(first_val)
label=t.Label(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="#125",fg="red",text="Slider 1 \nrange(0-100)\n")
label.grid(row=1,column=2)
label=t.Label(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="#125",fg="red",text="Slider 2 \nrange(100-200)")
label.grid(row=1,column=3)
label=t.Label(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="#125",fg="red",text="Slider 3 \nrange(200-300)")
label.grid(row=1,column=4)
label=t.Label(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="#125",fg="red",text="Sum of two slider(2&3)\n")
label.grid(row=1,column=5)
slide1=t.Scale(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="#125",fg="red", from_=0,to=100,resolution=0.5, orient=t.HORIZONTAL)
slide1.grid(row=2, column=2)
slide2=t.Scale(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="green",fg="#100", from_=100,to=200,resolution=1, orient=t.HORIZONTAL)
slide2.grid(row=2, column=3)
slide3=t.Scale(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="green",fg="#100", from_=200,to=300,resolution=1.5, orient=t.HORIZONTAL)
slide3.grid(row=2,column=4)
slide4=t.Scale(root,borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,bg="green",fg="#100", from_=0,to=500,resolution=2, orient=t.HORIZONTAL)
slide4.grid(row=2,column=5)
color="black"
labe2=t.Button(root,text="set slider to minimum value",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=clear,bg=color,fg="white")
labe2.grid(row=3,column=2)
labe2=t.Button(root,text="set slider to Maximum value",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=max,bg=color,fg="white")
labe2.grid(row=3,column=3)
labe2=t.Button(root,text="set slider to Avegrage value",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=avg,bg=color,fg="white")
labe2.grid(row=3,column=4)
button1=t.Button(root,text="Increment slider by 5\t",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=slide_add,bg=color,fg="white")
button1.grid(row=3,column=5)
button1=t.Button(root,text="Decrement slider by 5",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=slide_sub,bg=color,fg="white")
button1.grid(row=4,column=3)
button1=t.Button(root,text="Add slider 2 and slider 3",borderwidth=5,font=('Comic Sans MS',15,'bold'),relief=t.GROOVE,command=auto,bg=color,fg="white")
button1.grid(row=4,column=4)
root.mainloop()
